version: "3"
services:
  frontend:
    image: registry.gitlab.factory.social.gouv.fr/socialgouv/domifa/frontend:master
    ports:
      - 8080:80

  backend:
    env_file:
      - ./packages/backend/.env
    image: registry.gitlab.factory.social.gouv.fr/socialgouv/domifa/backend:master
    depends_on:
      - mongo
    ports:
      - 3000:3000

  mongo:
    image: "mongo:4.0.3"
    volumes:
      - domifa-data:/data/db

volumes:
  domifa-data:
