version: "3"
services:
  mongo:
    container_name: mongo
    image: "mongo:4.0.3"
    expose:
      - 27017
    ports:
      - "27017:27017"
    restart: always

  api:
    depends_on:
      - mongo
    container_name: api
    restart: always
    build: .
    ports:
      - "3000"
    links:
      - mongo
