version: "3"
services:
  frontend:
    image: registry.gitlab.factory.social.gouv.fr/socialgouv/domifa/frontend:b1e9526a5e4ab2a681c28bdc5bfddf9b78aff721
    restart: always
    ports:
      - 80:80

  backend:
    env_file:
      - ./packages/backend/.env
    image: registry.gitlab.factory.social.gouv.fr/socialgouv/domifa/backend:master
    restart: always
    depends_on:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - /mnt/files/:/files/

  mongo:
    image: "mongo:4.2.2"
    restart: always
    volumes:
      - domifa-data:/data/db
    ports:
      - 27017:27017

volumes:
  domifa-data:
