version: "3.2"
services:
  mongo:
    container_name: mongo
    image: "mongo:4.0.3"
    ports:
      - "27017:27017"
    restart: always
    build: .
    networks:
      - mongo

  api:
    depends_on:
      - mongo
    container_name: api
    restart: always
    build: .
    command: "yarn workspace @domifa/backend nodemon"
    ports:
      - "3000"
    links:
      - mongo

networks:
  mongo:
    external: true
