#

.prepare_stage: &prepare_stage
  extends: .base_register_stage
  stage: "Prepare"
  dependencies: []

#

Register socialgouv/domifa base image:
  <<: *prepare_stage
  variables:
    CONTEXT: .
    DOCKER_BUILD_ARGS: >-
      --shm-size 900M
    IMAGE_NAME: $CI_REGISTRY_IMAGE
