#

.quality_stage: &quality_stage
  stage: "Code Quality"
  dependencies: []

.master_based_stage: &master_based_stage
  variables:
    GIT_STRATEGY: none
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  before_script:
    - cd /app

###########################################
###                LINT                 ###
###########################################
Lint @domifa/frontend:
  <<: *quality_stage
  <<: *master_based_stage
  allow_failure: true
  script:
    - yarn workspace @domifa/frontend lint

Lint @domifa/backend:
  <<: *quality_stage
  <<: *master_based_stage
  allow_failure: true
  script:
    - yarn workspace @domifa/backend lint

###########################################
###                TESTS                ###
###########################################
Test @domifa/backend:
  <<: *quality_stage
  stage: "Integration test"
  <<: *master_based_stage
  services:
    - name: mongo:4.0.3
  variables:
    DB_USER: gitlab
    DB_PASS: test
    DB_HOST: localhost
    DB_PORT: 27017
  script:
    - apt-get install -y mongodb-org-tools
    - mongo domifa --eval "db.createUser({user:'${DB_USER}', pwd:'${DB_PASS}', roles:[{role:'readWrite', db:'domifa'}] });"
    - yarn workspace @domifa/backend test --coverage

Test @domifa/frontend:
  <<: *quality_stage
  stage: "Integration test"
  <<: *master_based_stage
  script:
    - yarn workspace @domifa/frontend test --coverage
