version: "3.2"
services:
  mongodb:
    image: "mongo:4.0.3"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongo"
      MONGO_INITDB_ROOT_PASSWORD: "mongo"
      MONGO_INITDB_DATABASE: "domifa"
    volumes:
      - /data/db
