version: "3.2"
services:
  api:
    depends_on:
      - mongo
    container_name: api
    restart: always
    build: .
    ports:
      - "3000"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: "mongo:4.0.3"
    ports:
      - "27017:27017"
